name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Dump environment info
        run: pnpm env

      - name: Build
        run: pnpm build
